### PR TITLE
DigitalOcean API v2 support

### PR DESCRIPTION
**Pull request by andrewchilds**
Upgrades Overcast to use the DigitalOcean API v2.

Requires a `DIGITALOCEAN_API_TOKEN` variable to be set:

```sh
$ overcast var set DIGITALOCEAN_API_TOKEN abc123
```

### CODE REVIEW

**Comment by garnold** [comment]
Hey @andrewchilds, something I've been meaning to ask you is why include `./node_modules` in the repo instead of just doing an `npm install` on checkout?

**Comment by andrewchilds** [comment]
Hey @garnold - bundling node_modules is the safest and easiest way to lock down dependencies and sub-dependencies. The other option is to use `npm shrinkwrap` - I'm sure that's the npm-approved approach, but I haven't looked into it yet. Otherwise even if you freeze your dependency versions, some dependency will not have frozen sub-dependencies (or sub-sub-dependencies), and eventually something in there will break due to some incompatibility.

**Comment by garnold** [comment]
Thanks @andrewchilds, makes sense. And I just saw your pull for `shrinkwrap`.

**Comment by garnold** [comment]
Thanks @andrewchilds, makes sense. And I just saw your pull for `shrinkwrap`.

**Comment by andrewchilds** [comment]
Yeah after I said that, I messed up the `package.json` in the 1.0 release so it was a good opportunity to give `shrinkwrap` a try :sweat_smile:

**Pull request merged**
